### ISSUE TITLE
Crashing app on first time when Android ask permission. Logcat inside.

### ISSUE THREAD

**Issue by claudioviola** [wymsee/cordova-imagePicker#126]
When try to open first time the album whit plugin the app crash and close sudnley.
The adb logcat report fllow lines.
Is it my fault?

02-01 22:12:05.709   778   966 I ActivityManager: START u0 {cmp=purple.alpha.app/com.synconset.MultiImageChooserActivity (has extras)} from uid 10174 on display 0
02-01 22:12:05.774   937  9461 E DatabaseUtils: Writing exception to parcel
02-01 22:12:05.774   937  9461 E DatabaseUtils: java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/images/media from pid=16354, uid=10174 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
02-01 22:12:05.774   937  9461 E DatabaseUtils: 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:605)
02-01 22:12:05.774   937  9461 E DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:480)
02-01 22:12:05.774   937  9461 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:211)
02-01 22:12:05.774   937  9461 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:112)
02-01 22:12:05.774   937  9461 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:453)
02-01 22:12:05.776   937  9458 E DatabaseUtils: Writing exception to parcel
02-01 22:12:05.776   937  9458 E DatabaseUtils: java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/images/media from pid=16354, uid=10174 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
02-01 22:12:05.776   937  9458 E DatabaseUtils: 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:605)
02-01 22:12:05.776   937  9458 E DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:480)
02-01 22:12:05.776   937  9458 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:211)
02-01 22:12:05.776   937  9458 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:112)
02-01 22:12:05.776   937  9458 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:453)
02-01 22:12:05.779 16354 16379 I Process : Sending signal. PID: 16354 SIG: 9
02-01 22:12:05.845   778   876 W InputDispatcher: channel '6a473c9 purple.alpha.app/purple.alpha.app.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
02-01 22:12:05.845   778   876 E InputDispatcher: channel '6a473c9 purple.alpha.app/purple.alpha.app.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
02-01 22:12:05.848   778   876 W InputDispatcher: channel '7c4d500 purple.alpha.app/com.synconset.MultiImageChooserActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
02-01 22:12:05.848   778   876 E InputDispatcher: channel '7c4d500 purple.alpha.app/com.synconset.MultiImageChooserActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
02-01 22:12:05.852   778   789 I WindowState: WIN DEATH: Window{7c4d500 u0 purple.alpha.app/com.synconset.MultiImageChooserActivity}
02-01 22:12:05.852   778   789 W InputDispatcher: Attempted to unregister already unregistered input channel '7c4d500 purple.alpha.app/com.synconset.MultiImageChooserActivity (server)'
02-01 22:12:05.854   778  1989 D GraphicsStats: Buffer count: 4
02-01 22:12:05.854   778  2008 I WindowState: WIN DEATH: Window{6a473c9 u0 purple.alpha.app/purple.alpha.app.MainActivity}
02-01 22:12:05.854   778  2008 W InputDispatcher: Attempted to unregister already unregistered input channel '6a473c9 purple.alpha.app/purple.alpha.app.MainActivity (server)'
02-01 22:12:05.870   778  1592 I ActivityManager: Process purple.alpha.app (pid 16354) has died
02-01 22:12:05.871   778  1592 W ActivityManager: Force removing ActivityRecord{7301394 u0 purple.alpha.app/com.synconset.MultiImageChooserActivity t656}: app died, no saved state
02-01 22:12:05.871   778  1592 W ActivityManager: Force removing ActivityRecord{68ae170 u0 purple.alpha.app/.MainActivity t656}: app died, no saved state
02-01 22:12:05.918   778   788 W InputMethodManagerService: Got RemoteException sending setActive(false) notification to pid 16354 uid 10174
02-01 22:12:05.919  1893  1893 I Keyboard.Facilitator: onFinishInput()
02-01 22:12:06.350   778   799 W WindowAnimator: Failed to dispatch window animation state change.
02-01 22:12:06.350   778   799 W WindowAnimator: android.os.DeadObjectException
02-01 22:12:06.350   778   799 W WindowAnimator: 	at android.os.BinderProxy.transactNative(Native Method)
02-01 22:12:06.350   778   799 W WindowAnimator: 	at android.os.BinderProxy.transact(Binder.java:503)
02-01 22:12:06.350   778   799 W WindowAnimator: 	at android.view.IWindow$Stub$Proxy.onAnimationStopped(IWindow.java:534)
02-01 22:12:06.350   778   799 W WindowAnimator: 	at com.android.server.wm.WindowAnimator.updateWindowsLocked(WindowAnimator.java:286)
02-01 22:12:06.350   778   799 W WindowAnimator: 	at com.android.server.wm.WindowAnimator.animateLocked(WindowAnimator.java:678)
02-01 22:12:06.350   778   799 W WindowAnimator: 	at com.android.server.wm.WindowAnimator.-wrap0(WindowAnimator.java)
02-01 22:12:06.350   778   799 W WindowAnimator: 	at com.android.server.wm.WindowAnimator$1.doFrame(WindowAnimator.java:123)
02-01 22:12:06.350   778   799 W WindowAnimator: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:856)
02-01 22:12:06.350   778   799 W WindowAnimator: 	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
02-01 22:12:06.350   778   799 W WindowAnimator: 	at android.view.Choreographer.doFrame(Choreographer.java:603)
02-01 22:12:06.350   778   799 W WindowAnimator: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
02-01 22:12:06.350   778   799 W WindowAnimator: 	at android.os.Handler.handleCallback(Handler.java:739)
02-01 22:12:06.350   778   799 W WindowAnimator: 	at android.os.Handler.dispatchMessage(Handler.java:95)
02-01 22:12:06.350   778   799 W WindowAnimator: 	at android.os.Looper.loop(Looper.java:148)
02-01 22:12:06.350   778   799 W WindowAnimator: 	at android.os.HandlerThread.run(HandlerThread.java:61)
02-01 22:12:06.350   778   799 W WindowAnimator: 	at com.android.server.ServiceThread.run(ServiceThread.java:46)
02-01 22:12:06.350   778   799 W WindowAnimator: Failed to dispatch window animation state change.
02-01 22:12:06.350   778   799 W WindowAnimator: android.os.DeadObjectException
02-01 22:12:06.350   778   799 W WindowAnimator: 	at android.os.BinderProxy.transactNative(Native Method)
02-01 22:12:06.350   778   799 W WindowAnimator: 	at android.os.BinderProxy.transact(Binder.java:503)
02-01 22:12:06.350   778   799 W WindowAnimator: 	at android.view.IWindow$Stub$Proxy.onAnimationStopped(IWindow.java:534)
02-01 22:12:06.350   778   799 W WindowAnimator: 	at com.android.server.wm.WindowAnimator.updateWindowsLocked(WindowAnimator.java:286)
02-01 22:12:06.350   778   799 W WindowAnimator: 	at com.android.server.wm.WindowAnimator.animateLocked(WindowAnimator.java:678)
02-01 22:12:06.350   778   799 W WindowAnimator: 	at com.android.server.wm.WindowAnimator.-wrap0(WindowAnimator.java)
02-01 22:12:06.350   778   799 W WindowAnimator: 	at com.android.server.wm.WindowAnimator$1.doFrame(WindowAnimator.java:123)
02-01 22:12:06.350   778   799 W WindowAnimator: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:856)
02-01 22:12:06.350   778   799 W WindowAnimator: 	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
02-01 22:12:06.350   778   799 W WindowAnimator: 	at android.view.Choreographer.doFrame(Choreographer.java:603)
02-01 22:12:06.350   778   799 W WindowAnimator: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
02-01 22:12:06.350   778   799 W WindowAnimator: 	at android.os.Handler.handleCallback(Handler.java:739)
02-01 22:12:06.350   778   799 W WindowAnimator: 	at android.os.Handler.dispatchMessage(Handler.java:95)
02-01 22:12:06.350   778   799 W WindowAnimator: 	at android.os.Looper.loop(Looper.java:148)
02-01 22:12:06.350   778   799 W WindowAnimator: 	at android.os.HandlerThread.run(HandlerThread.java:61)
02-01 22:12:06.350   778   799 W WindowAnimator: 	at com.android.server.ServiceThread.run(ServiceThread.java:46)

**Comment by jonnyhsy** [comment]
+1, same issue found.

**Comment by Findiglay** [comment]
+1 also getting crashes now with Android 6.0.1 when trying to use the image picker. Permissions are not being requested when launching the image picker it seems.

**Comment by freiserg** [comment]
Have you tried to add this code https://github.com/wymsee/cordova-imagePicker/issues/127#issuecomment-191925667 in config.xml?

**Comment by Findiglay** [comment]
This above solution does not solve the issue. The build goes fine and the app is working. There is no permissions priming being fired for access to images, however, and it seems when it tries to launch the plugin without permissions given, a crash occurs.

**Comment by claudioviola** [comment]
Months ago I tried window.plugins.ImagePicker and not window.ImagePicker. 
window.plugins.ImagePicker exists - so changing to that would probably fix it for now at least on Android
At moment I'm not focus on picker image feature on my project, when I come back on it I can track again my log

**Comment by Findiglay** [comment]
I've just tested Poocart's [pull request](https://github.com/wymsee/cordova-imagePicker/pull/136), which fixes the issue for me. There is a native permissions popup and denying permission will no longer crash the app.

**Comment by mohanchalla** [comment]
@Findiglay  Hi! is that solution is working fine for you without any issues. Even I am also facing the same issue.

**Comment by Findiglay** [comment]
@mohanchalla Yes, its working without any problems so far. I've forked the repo and merged Poocarts branch to master here - https://github.com/Findiglay/cordova-imagePicker/branches

**Comment by mohanchalla** [comment]
@Findiglay If I say like below will it download Findiglay/cordova-imagePicker right.

cordova plugin add cordova-plugin-image-picker

**Comment by Findiglay** [comment]
Nope, you want to just use: cordova plugin add
https://github.com/Findiglay/cordova-imagePicker.git

*Grant Findlay*
*Developer*

[image: It's time to decide! Click here to find out more!]
<https://decidz.com/>

*Web:* www.decidz.com
*Call:* +44 (0)7512378624 <+447512378624>

**Comment by salilmalik** [comment]
Hi @Findiglay 

I removed the imagePicker plugin and used cordova plugin add ttps://github.com/Findiglay/cordova-imagePicker.git and when I use the ionic build android command it generates the androidManifest.xml file

In the androidManifest.xml I see   <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" /> instead of READ_EXTERNAL_STORAGE so I added 
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" /> manually and used ionic run android but still the app is crashing.

Also I am getting the following error : C:\App\platforms\android\src\com\synconset\MultiImageChooserActivity.java uses unchecked or unsafe operations.

**Comment by danielgolub** [comment]
Anyone been able to solve it?
I still get crash if user haven't approved access to Photos first.

**Comment by richardmarais** [comment]
@danielgolub, I have the same issue. Have you found a solution yet?

**Comment by imarem** [comment]
use a fork by @Findiglay cordova plugin add https://github.com/Findiglay/cordova-imagePicker.git, works fine!

**Comment by amostech** [comment]
@Findiglay thank you for forking and including a solution to this issue. I am using your forked version because it includes the READ_EXTERNAL_STORAGE permissions that I need for Android. But I think that this should be merged in the main stream of the plugin ASAP. Lots of people should be getting the same error in Android 6+

**Comment by arthur-cheung** [comment]
@Findiglay, your version appears to work for Android, and newer iOS devices. But on older ones it crashes. All were on OS versions were 10.2.1, just different hardware. iPhone 7 was fine, but iPhone 6 and iPad 2 was not.

Investigating now to see if I can find out further what's going on.

EDIT: It looks like this forked fix has opposite effect on iOS. It wasn't so much newer iOS device that was okay, but it was a device that had permissions set already. This forked plugin was in fact crashing on iOS when it required permissions. So what it fixed for Android, appears to be crashing for iOS.

**Comment by usmanmirza** [comment]
Hi @Findiglay while adding the plugin I'm getting this error.

`(node:7376) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): CordovaError: Failed to fetch plugin https://github.com/Findiglay/cordova-imagePicker.git via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: cmd: Command failed with exit code 1 Error output:
npm ERR! code ENOGIT
npm ERR! No git binary found in $PATH
npm ERR!
npm ERR! Failed using git.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\usman\AppData\Roaming\npm-cache\_logs\2018-03-13T08_34_15_168Z-debug.log
(node:7376) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by gifthlong** [comment]
since  https://github.com/Findiglay/cordova-imagePicker.git has been removed from github. Anyone knows of an alternative?

**Comment by renzified** [comment]
the forked link is broken pls fix i need it asap thanks in advance
