### ISSUE TITLE
andriod Marshmallow-  call imagePicker.getPictures : error while executing doInBackground

### ISSUE THREAD

**Issue by devshisiyani** [wymsee/cordova-imagePicker#148]
Works fine on all other android devices and os (kitkat, lollipop etc)
Does not work on Marshmallow.
Call window.imagePicker.getPictures(
		function(results) {
			for (var i = 0; i < results.length; i++) {
				var url =  results[i];
				var currentDir = url.substr(0, url.lastIndexOf('/'));
				var currentName = url.substr(url.lastIndexOf('/')+1);
				Addcnt++;
				localStorage.Addcnt=Addcnt;
				var newName = "Image_" + pad(Addcnt) + ".jpg";
				PrintDebug('AddImage Image URI: ' + results[i]+", newName:"+newName);
				renameURI_File(url, currentDir, newName);
			}

get error
E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #2
                                                                         Process: com.phonegap.dailydarshan, PID: 2779
                                                                         java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                             at android.os.AsyncTask$3.done(AsyncTask.java:309)
                                                                             at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                                             at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                                             at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                             at java.lang.Thread.run(Thread.java:818)
                                                                          Caused by: java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/images/media from pid=2779, uid=10058 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
                                                                             at android.os.Parcel.readException(Parcel.java:1599)
                                                                             at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
                                                                             at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
                                                                             at android.content.ContentProviderProxy.query(ContentProviderNative.java:421)
                                                                             at android.content.ContentResolver.query(ContentResolver.java:491)
                                                                             at android.content.CursorLoader.loadInBackground(CursorLoader.java:64)
                                                                             at android.content.CursorLoader.loadInBackground(CursorLoader.java:56)
                                                                             at android.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:312)
                                                                             at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:69)
                                                                             at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:66)
                                                                             at android.os.AsyncTask$2.call(AsyncTask.java:295)

**Comment by HugoSTorres** [comment]
I added the following line to the plugin's plugin.xml to fix this:
```
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
```

I added it in config-file[target="AndroidManifest.xml"] underneath the permission for WRITE_EXTERNAL_STORAGE.

However, even after adding that, the call to getPictures is still causing a crash for me. I'm gonna continue investigating to see what I can dig up.

**Comment by devshisiyani** [comment]
Have fixed this issue now. U need to call function checkselfpermission.. if not granted then call requestpermission with read_external_storage. Once the user gives permission then imagepicker should work. Let me  know if u need code snippets

**Comment by HugoSTorres** [comment]
@devshisiyani yeah some snippets would help I think. I can't seem to find that function anywhere in the code.

**Comment by BugsBunnyBR** [comment]
maybe it helps
https://github.com/lukaslisowski/cordova-plugin-email-composer/pull/5/files

**Comment by devshisiyani** [comment]
In the Imagepicker.java
include 
import android.os.Build;
import android.content.pm.PackageManager;
import android.Manifest;
import android.support.v4.app.ActivityCompat;
import android.support.v4.content.ContextCompat;
import android.content.DialogInterface;

You can call the function chkPerm_storeread. First time it asks the user to grant access. Thereafter store access will always be granted.
private boolean chkPerm_storeread (final CallbackContext callbackContext) {
		Log.i("imagePicker", "called chkPerm_storeread");
		if (Build.VERSION.SDK_INT >= 23) {
			int permissionCheck = ContextCompat.checkSelfPermission(this.cordova.getActivity(),
					Manifest.permission.READ_EXTERNAL_STORAGE);
			if (permissionCheck != PackageManager.PERMISSION_GRANTED) {
				ActivityCompat.requestPermissions(this.cordova.getActivity(),new String[]{Manifest.permission.READ_EXTERNAL_STORAGE}, REQUEST_STORAGE);
				//boolean ans = handleStoragePerms();
				callbackContext.error("Permission for storage read requested");
			} else {
				Log.v("chkPerm_storeread", "Permission is granted");
				callbackContext.success("Check permission storage read success");
			}
		} else {callbackContext.success("Check permission storage read success");}
		return true;
	}

**Comment by amitonkare** [comment]
@devshisiyani 
Hey! 
where should i call chkPerm_storeread  function? on the first line on execute() ?
I am not a android developer. Sorry if the questions is very basic.

**Comment by zoeticclarence** [comment]
I have found an easier way to request permission. 
Check out https://www.npmjs.com/package/cordova-plugin-android-permissions.
Use the plugin to request or check permission before calling window.imagePicker.getPictures. 
It does the trick for me.

**Comment by idiglove** [comment]
> I have found an easier way to request permission.
> Check out https://www.npmjs.com/package/cordova-plugin-android-permissions.
> Use the plugin to request or check permission before calling window.imagePicker.getPictures.
> It does the trick for me.

You saved my life. Been looking for a solution for this for hours. Cheers!
