### ISSUE TITLE
When Cordova activity went to background by this plugin, the app crashed.

### ISSUE THREAD

**Issue by Fogrunner** [wymsee/cordova-imagePicker#156]
When i was testing my app in low memory scenario. I encountered this issue. 

Scenario 

1. i opened my app.
2. i ran this plugin and then main activity switched to background.
3. i pushed home button.
4. i wasted memory usage of my device in order to make low memory scenario.
5. i checked main activity of my app is killed exactly.
6. i switched to my app. and i could see this plugin.
7. i closed this plugin. 
8. my app was crashed!

does anyone have any idea of this issue?

**Comment by Fogrunner** [comment]
#94

**Comment by Fogrunner** [comment]
06-21 08:04:59.909 27337-27337/kr.co.paransoft.edit E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: kr.co.paransoft.edit, PID: 27337
                                                                      java.lang.RuntimeException: Unable to resume activity {kr.co.paransoft.edit/kr.co.paransoft.edit.MainActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=0, result=0, data=null} to activity {kr.co.paransoft.edit/kr.co.paransoft.edit.MainActivity}: java.lang.NullPointerException
                                                                          at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3076)
                                                                          at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3105)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                          at android.app.ActivityThread.access$900(ActivityThread.java:175)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                          at android.os.Looper.loop(Looper.java:146)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5602)
                                                                          at java.lang.reflect.Method.invokeNative(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:515)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
                                                                          at dalvik.system.NativeStart.main(Native Method)
                                                                       Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=0, result=0, data=null} to activity {kr.co.paransoft.edit/kr.co.paransoft.edit.MainActivity}: java.lang.NullPointerException
                                                                          at android.app.ActivityThread.deliverResults(ActivityThread.java:3681)
                                                                          at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3063)
                                                                          at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3105) 
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                          at android.app.ActivityThread.access$900(ActivityThread.java:175) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                          at android.os.Looper.loop(Looper.java:146) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5602) 
                                                                          at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                          at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099) 
                                                                          at dalvik.system.NativeStart.main(Native Method) 
                                                                       Caused by: java.lang.NullPointerException
                                                                          at com.synconset.ImagePicker.onActivityResult(ImagePicker.java:67)
                                                                          at org.apache.cordova.CordovaInterfaceImpl.onActivityResult(CordovaInterfaceImpl.java:151)
                                                                          at org.apache.cordova.CordovaActivity.onActivityResult(CordovaActivity.java:348)
                                                                          at android.app.Activity.dispatchActivityResult(Activity.java:5643)
                                                                          at android.app.ActivityThread.deliverResults(ActivityThread.java:3677)
                                                                          at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3063) 
                                                                          at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3105) 
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                          at android.app.ActivityThread.access$900(ActivityThread.java:175) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                          at android.os.Looper.loop(Looper.java:146) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5602) 
                                                                          at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                          at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099) 
                                                                          at dalvik.system.NativeStart.main(Native Method)

**Comment by Fogrunner** [comment]
in order to resolve it, it is necessary to add some codes to 'ImagePicker.java' file like below.

```
import android.os.Bundle;

public Bundle onSaveInstanceState() 
{
    Bundle state = new Bundle();
    return state;
}

public void onRestoreStateForActivityResult(Bundle state, CallbackContext callbackContext) 
{
    this.callbackContext = callbackContext;
}

```

i have tested it works well in android. but, i am not sure ios as well.
