### ISSUE TITLE
app crash on android  4.4.4 

### ISSUE THREAD

**Issue by fenglu09** [wymsee/cordova-imagePicker#188]
Android： 4.4.4
plugin version: 1.1.1

Anyone can help me?

logcat：

```
 E/AndroidRuntime: FATAL EXCEPTION: pool-2-thread-14
                                                                     Process: com.XXX.XXX, PID: 10642
                                                                     java.lang.RuntimeException: An error occured while executing doInBackground()
                                                                         at android.os.AsyncTask$3.done(AsyncTask.java:300)
                                                                         at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
                                                                         at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
                                                                         at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                         at java.lang.Thread.run(Thread.java:848)
                                                                      Caused by: java.util.ConcurrentModificationException
                                                                         at java.util.HashMap$HashIterator.nextEntry(HashMap.java:806)
                                                                         at java.util.HashMap$ValueIterator.next(HashMap.java:838)
                                                                         at android.media.MiniThumbFile.deactivate(MiniThumbFile.java:198)
                                                                         at android.provider.MediaStore$InternalThumbnails.getThumbnail(MediaStore.java:780)
                                                                         at android.provider.MediaStore$Images$Thumbnails.getThumbnail(MediaStore.java:1171)
                                                                         at com.synconset.ImageFetcher$BitmapFetcherTask.doInBackground(ImageFetcher.java:186)
                                                                         at com.synconset.ImageFetcher$BitmapFetcherTask.doInBackground(ImageFetcher.java:164)
                                                                         at android.os.AsyncTask$2.call(AsyncTask.java:288)
                                                                         at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                         at java.lang.Thread.run(Thread.java:848) 
```

**Comment by fenglu09** [comment]
Is there anyone who can help me？

**Comment by D4rthR4tz3** [comment]
Did you select an image after dismissing the ProgressDialog? Then my pull request might help you :)

**Comment by fenglu09** [comment]
No， I just scroll the view， then it crashed
