### ISSUE TITLE
outofmemory

### ISSUE THREAD

**Issue by lembasgithub** [wymsee/cordova-imagePicker#20]
Hi,

Even if I select one photo, I get the folowing error. My phone is samsung s4 mini. Android 4.2.2.
I can run any other program, no memory problem occurs. Any suggestions?

08-08 16:42:55.745: E/AndroidRuntime(28036): FATAL EXCEPTION: AsyncTask #4
08-08 16:42:55.745: E/AndroidRuntime(28036): java.lang.RuntimeException: An error occured while executing doInBackground()
08-08 16:42:55.745: E/AndroidRuntime(28036):    at android.os.AsyncTask$3.done(AsyncTask.java:299)
08-08 16:42:55.745: E/AndroidRuntime(28036):    at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:352)
08-08 16:42:55.745: E/AndroidRuntime(28036):    at java.util.concurrent.FutureTask.setException(FutureTask.java:219)
08-08 16:42:55.745: E/AndroidRuntime(28036):    at java.util.concurrent.FutureTask.run(FutureTask.java:239)
08-08 16:42:55.745: E/AndroidRuntime(28036):    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
08-08 16:42:55.745: E/AndroidRuntime(28036):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
08-08 16:42:55.745: E/AndroidRuntime(28036):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
08-08 16:42:55.745: E/AndroidRuntime(28036):    at java.lang.Thread.run(Thread.java:856)
08-08 16:42:55.745: E/AndroidRuntime(28036): Caused by: java.lang.OutOfMemoryError
08-08 16:42:55.745: E/AndroidRuntime(28036):    at android.graphics.Bitmap.nativeCreate(Native Method)
08-08 16:42:55.745: E/AndroidRuntime(28036):    at android.graphics.Bitmap.createBitmap(Bitmap.java:718)
08-08 16:42:55.745: E/AndroidRuntime(28036):    at android.graphics.Bitmap.createBitmap(Bitmap.java:695)
08-08 16:42:55.745: E/AndroidRuntime(28036):    at android.graphics.Bitmap.createBitmap(Bitmap.java:628)
08-08 16:42:55.745: E/AndroidRuntime(28036):    at com.synconset.MultiImageChooserActivity$ResizeImagesTask.doInBackground(MultiImageChooserActivity.java:535)
08-08 16:42:55.745: E/AndroidRuntime(28036):    at com.synconset.MultiImageChooserActivity$ResizeImagesTask.doInBackground(MultiImageChooserActivity.java:485)
08-08 16:42:55.745: E/AndroidRuntime(28036):    at android.os.AsyncTask$2.call(AsyncTask.java:287)
08-08 16:42:55.745: E/AndroidRuntime(28036):    at java.util.concurrent.FutureTask.run(FutureTask.java:234)
08-08 16:42:55.745: E/AndroidRuntime(28036):    ... 4 more
08-08 16:42:56.085: E/android.os.Debug(775): !@Dumpstate > sdumpstate -k -t -z -d -o /data/log/dumpstate_app_error

**Comment by imhassan** [comment]
I am getting OutOfMemory Exception for images that are high resolution. 
Device is android os 4.0, cordova version 4.2

E/dalvikvm-heap( 3822): Out of memory on a 10219216-byte allocation.
E/dalvikvm( 3822): Out of memory: Heap Size=62535KB, Allocated=54218KB, Limit=65536KB
E/dalvikvm( 3822): Extra info: Footprint=58503KB, Allowed Footprint=62535KB, Trimmed=1544KB
E/Bitmap_JNI( 3822): Create Bitmap Failed.
E/Bitmap_JNI( 3822): Failed to create SkBitmap!
E/dalvikvm-heap( 3822): Out of memory on a 24023056-byte allocation.
E/dalvikvm( 3822): Out of memory: Heap Size=62535KB, Allocated=54250KB, Limit=65536KB
E/dalvikvm( 3822): Extra info: Footprint=58503KB, Allowed Footprint=62535KB, Trimmed=1544KB
E/dalvikvm-heap( 3822): Out of memory on a 24023056-byte allocation.
E/dalvikvm( 3822): Out of memory: Heap Size=62535KB, Allocated=54250KB, Limit=65536KB
E/dalvikvm( 3822): Extra info: Footprint=58503KB, Allowed Footprint=62535KB, Trimmed=1544KB
E/Trace   ( 3976): error opening trace file: No such file or directory (2)

**Comment by stromgren** [comment]
I'm also getting this error on multiple versions. Here is a log output from 5.01. In my case the images are fairly large around 10-14MB. If i select only a few images the same errors are throws, but the app doesn't crash. When i select more than 6 images, the app dies.

I'm running this in the simulator with 2GB of memory.

```
I/art     ( 2118): Forcing collection of SoftReferences for 76MB allocation
I/art     ( 2118): Alloc concurrent mark sweep GC freed 488(19KB) AllocSpace objects, 0(0B) LOS objects, 32% free, 8MB/12MB, paused 0 total 20ms
E/art     ( 2118): Throwing OutOfMemoryError "Failed to allocate a 79847436 byte allocation with 4194304 free bytes and 55MB until OOM"
D/skia    ( 2118): --- decoder->decode returned false
I/art     ( 2118): Alloc partial concurrent mark sweep GC freed 43(1776B) AllocSpace objects, 2(19MB) LOS objects, 32% free, 8MB/12MB, paused 0 total 100ms
E/art     ( 2118): Throwing OutOfMemoryError "Failed to allocate a 71663628 byte allocation with 4194304 free bytes and 55MB until OOM"
D/skia    ( 2118): --- decoder->decode returned false
I/art     ( 2118): Alloc partial concurrent mark sweep GC freed 26(1152B) AllocSpace objects, 2(17MB) LOS objects, 32% free, 8MB/12MB, paused 100ms total 100ms
E/art     ( 2118): Throwing OutOfMemoryError "Failed to allocate a 71663628 byte allocation with 4194304 free bytes and 55MB until OOM"
D/skia    ( 2118): --- decoder->decode returned false
I/art     ( 2118): Alloc concurrent mark sweep GC freed 6(192B) AllocSpace objects, 0(0B) LOS objects, 32% free, 8MB/12MB, paused 0 total 100ms
I/art     ( 2118): Forcing collection of SoftReferences for 76MB allocation
I/art     ( 2118): Alloc sticky concurrent mark sweep GC freed 54(10KB) AllocSpace objects, 1(16KB) LOS objects, 6% free, 27MB/29MB, paused 100ms total 100ms
I/art     ( 2118): Alloc partial concurrent mark sweep GC freed 18(640B) AllocSpace objects, 2(46MB) LOS objects, 32% free, 8MB/12MB, paused 0 total 100ms
I/art     ( 2118): Alloc concurrent mark sweep GC freed 3(96B) AllocSpace objects, 0(0B) LOS objects, 32% free, 8MB/12MB, paused 0 total 110ms
E/art     ( 2118): Throwing OutOfMemoryError "Failed to allocate a 71663628 byte allocation with 4194304 free bytes and 55MB until OOM"
D/skia    ( 2118): --- decoder->decode returned false
I/art     ( 2118): Alloc partial concurrent mark sweep GC freed 26(1152B) AllocSpace objects, 2(17MB) LOS objects, 32% free, 8MB/12MB, paused 0 total 110ms
I/art     ( 2118): Forcing collection of SoftReferences for 76MB allocation
I/art     ( 2118): Alloc partial concurrent mark sweep GC freed 27(1200B) AllocSpace objects, 2(19MB) LOS objects, 32% free, 8MB/12MB, paused 0 total 100ms
I/art     ( 2118): Forcing collection of SoftReferences for 76MB allocation
I/art     ( 2118): Alloc concurrent mark sweep GC freed 3(96B) AllocSpace objects, 0(0B) LOS objects, 32% free, 8MB/12MB, paused 0 total 90ms
E/art     ( 2118): Throwing OutOfMemoryError "Failed to allocate a 79847436 byte allocation with 4194304 free bytes and 55MB until OOM"
D/skia    ( 2118): --- decoder->decode returned false
I/art     ( 2118): Alloc concurrent mark sweep GC freed 6(192B) AllocSpace objects, 0(0B) LOS objects, 32% free, 8MB/12MB, paused 0 total 100ms
I/art     ( 2118): Forcing collection of SoftReferences for 76MB allocation
D/CordovaActivity( 2118): Resuming the App
W/EGL_emulation( 2118): eglSurfaceAttrib not implemented
W/OpenGLRenderer( 2118): Failed to set EGL_SWAP_BEHAVIOR on surface 0x7f4f7d3c0e80, error=EGL_SUCCESS
E/eglCodecCommon( 2118): glUtilsParamSize: unknow param 0x00000b44
E/eglCodecCommon( 2118): glUtilsParamSize: unknow param 0x00000bd0
E/eglCodecCommon( 2118): glUtilsParamSize: unknow param 0x00000b44
E/eglCodecCommon( 2118): glUtilsParamSize: unknow param 0x00000bd0
E/eglCodecCommon( 2118): **** ERROR unknown type 0x0 (glSizeof,72)
D/SoftKeyboardDetect( 2118): Ignore this event
I/art     ( 2118): Clamp target GC heap from 64MB to 64MB
I/art     ( 2118): Clamp target GC heap from 64MB to 64MB
I/art     ( 2118): Clamp target GC heap from 64MB to 64MB
I/art     ( 2118): Forcing collection of SoftReferences for 19MB allocation
I/art     ( 2118): Clamp target GC heap from 64MB to 64MB
I/art     ( 2118): Alloc concurrent mark sweep GC freed 27(1552B) AllocSpace objects, 1(16KB) LOS objects, 5% free, 60MB/64MB, paused 0 total 110ms
I/art     ( 2118): WaitForGcToComplete blocked for 100ms for cause Alloc
I/art     ( 2118): Clamp target GC heap from 64MB to 64MB
W/ActivityManager( 1302):   Force finishing activity se.natverkteknik.fotoapp/.MainActivity
E/gralloc_goldfish(  947): gralloc_alloc: Mismatched usage flags: 576 x 576, usage 333
W/GraphicBufferAllocator(  947): alloc(576, 576, 1, 00000333, ...) failed -22 (Invalid argument)
E/        (  947): GraphicBufferAlloc::createGraphicBuffer(w=576, h=576) failed (Invalid argument), handle=0x0
I/OpenGLRenderer( 1302): Initialized EGL, version 1.4
I/art     ( 2118): Clamp target GC heap from 64MB to 64MB
I/art     ( 2118): Alloc concurrent mark sweep GC freed 134(24KB) AllocSpace objects, 0(0B) LOS objects, 5% free, 60MB/64MB, paused 0 total 40ms
I/art     ( 2118): Forcing collection of SoftReferences for 4MB allocation
I/ActivityManager( 1302): Process se.natverkteknik.fotoapp (pid 2118) has died
```

**Comment by Heshyo** [comment]
The OutOfMemory issue when working with images is quite common in Android. Event the official camera plugin can crash the app (or at least it used to on some phone with high res sensors) if you ask it to resize or rotate the image, as well as plugins used to resize images.

You could try adding ```<application android:largeHeap="true" />``` to your manifest, or avoid rotating/resizing/compressing the images.
