### ISSUE TITLE
Selecting photos in non-default orientation causes a crash

### ISSUE THREAD

**Issue by Spriz** [wymsee/cordova-imagePicker#217]
If using non-default orientation on your device (landscape on phones or portait on tablets) the app is crashing whenever photos has been selected.

# Stacktraces

## 7.0
```
java.lang.IllegalArgumentException: View=DecorView@6355e25[Processing images] not attached to window manager
	at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:473)
	at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:382)
	at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:126)
	at android.app.Dialog.dismissDialog(Dialog.java:363)
	at android.app.Dialog.dismiss(Dialog.java:346)
	at com.synconset.MultiImageChooserActivity$ResizeImagesTask.onPostExecute(MultiImageChooserActivity.java:618)
	at com.synconset.MultiImageChooserActivity$ResizeImagesTask.onPostExecute(MultiImageChooserActivity.java:508)
	at android.os.AsyncTask.finish(AsyncTask.java:667)
	at android.os.AsyncTask.-wrap1(AsyncTask.java)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:684)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6176)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
```

## 4.0
```
java.lang.IllegalArgumentException: View=com.android.internal.policy.impl.PhoneWindow$DecorView{42377348 V.E..... R.....I. 0,0-624,243} not attached to window manager
	at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:389)
	at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:318)
	at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:84)
	at android.app.Dialog.dismissDialog(Dialog.java:420)
	at android.app.Dialog.dismiss(Dialog.java:403)
	at com.synconset.MultiImageChooserActivity$ResizeImagesTask.onPostExecute(MultiImageChooserActivity.java:618)
	at com.synconset.MultiImageChooserActivity$ResizeImagesTask.onPostExecute(MultiImageChooserActivity.java:508)
	at android.os.AsyncTask.finish(AsyncTask.java:632)
	at android.os.AsyncTask.access$600(AsyncTask.java:177)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:146)
	at android.app.ActivityThread.main(ActivityThread.java:5593)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by schnouz** [comment]
Got the same problem, Have you found any solution ?

**Comment by Spriz** [comment]
Not really @musecz - I'm planning to clean up a bit at some point, but I'm not skilled in Android/Java :)

**Comment by schnouz** [comment]
@Spriz For now If you need to have an imagePicker for ionic2 you could alternatively use @ionic-native/camera. An exemple of the implementation can be found there : http://blog.ionic.io/ionic-native-accessing-ios-photos-and-android-gallery-part-i/

**Comment by Spriz** [comment]
@musecz we're on Ionic 1 unfortunately :)

**Comment by cherylhanlon** [comment]
I am facing this issue too - is there any news on it ? Thanks.
