### ISSUE TITLE
crashed when choose a image 

### ISSUE THREAD

**Issue by fengyanliang** [wymsee/cordova-imagePicker#249]
Please help me on this, thanks.

D/skia: jpeg_decoder mode 1, config 6, w 320, h 200, sample 1, bsLength 4d56!!
D/skia: jpeg_decoder finish successfully, L:1879!!!
E/CursorLeakDetecter: PossibleCursorLeak:content://media/external/images/thumbnails,QueryCounter:5
                      android.database.sqlite.DatabaseObjectNotClosedException: Application did not close the cursor or database object that was opened here
                          at android.content.ContentResolver.query(ContentResolver.java:491)
                          at android.content.ContentResolver.query(ContentResolver.java:405)
                          at android.provider.MediaStore$InternalThumbnails.getThumbnail(MediaStore.java:682)
                          at android.provider.MediaStore$Images$Thumbnails.getThumbnail(MediaStore.java:1171)
                          at com.synconset.ImageFetcher$BitmapFetcherTask.doInBackground(ImageFetcher.java:186)
                          at com.synconset.ImageFetcher$BitmapFetcherTask.doInBackground(ImageFetcher.java:164)
                          at android.os.AsyncTask$2.call(AsyncTask.java:288)
                          at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                          at java.lang.Thread.run(Thread.java:841)
V/MiniThumbFile: deactivate() begin
V/MiniThumbFile: deactivate() begin
V/MiniThumbFile: deactivate() end
V/MiniThumbFile: deactivate() begin
V/MiniThumbFile: deactivate() begin
V/MiniThumbFile: deactivate() end
V/MiniThumbFile: deactivate() end
V/MiniThumbFile: deactivate() end
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: io.ionic.starter, PID: 8503
                  java.lang.IllegalArgumentException: View=com.android.internal.policy.impl.PhoneWindow$DecorView{420fff40 V.E..... R.....I. 0,0-761,214} not attached to window manager
                      at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:372)
                      at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:301)
                      at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:84)
                      at android.app.Dialog.dismissDialog(Dialog.java:340)
                      at android.app.Dialog.dismiss(Dialog.java:323)
                      at com.synconset.MultiImageChooserActivity$ResizeImagesTask.onPostExecute(MultiImageChooserActivity.java:618)
                      at com.synconset.MultiImageChooserActivity$ResizeImagesTask.onPostExecute(MultiImageChooserActivity.java:508)
                      at android.os.AsyncTask.finish(AsyncTask.java:632)
                      at android.os.AsyncTask.access$600(AsyncTask.java:177)
                      at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
                      at android.os.Handler.dispatchMessage(Handler.java:110)
                      at android.os.Looper.loop(Looper.java:193)
                      at android.app.ActivityThread.main(ActivityThread.java:5323)
                      at java.lang.reflect.Method.invokeNative(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:515)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:828)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:644)
                      at dalvik.system.NativeStart.main(Native Method)
D/skia: jpeg_decoder mode 1, config 6, w 320, h 200, sample 1, bsLength 3251!!
D/skia: jpeg_decoder finish successfully, L:1879!!!
V/MiniThumbFile: deactivate() begin
V/MiniThumbFile: deactivate() end

**Comment by abhishek1234321** [comment]
any luck with this?
